# Generated by Django 5.2.9 on 2025-12-18 20:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0002_favorite"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="interests",
            field=models.ManyToManyField(
                blank=True, related_name="interested_students", to="events.tag"
            ),
        ),
    ]
