from django.db import migrations

DEFAULT_TAGS = [
    "yapay zeka",
    "robotik",
    "veri bilimi",
    "makine öğrenmesi",
    "web geliştirme",
    "mobil uygulama",
    "tasarım",
    "grafik tasarım",
    "fotoğrafçılık",
    "video prodüksiyon",
    "girişimcilik",
    "start-up",
    "kariyer",
    "staj",
    "mentorluk",
    "hackathon",
    "atölye",
    "seminer",
    "konferans",
    "etkinlik yönetimi",
    "projeler",
    "topluluk hizmeti",
    "gönüllülük",
    "spor",
    "futbol",
    "basketbol",
    "voleybol",
    "yüzme",
    "yoga",
    "sağlık",
    "psikoloji",
    "medya",
    "muzik",
    "koru",
    "orchestra",
    "tiyatro",
    "sahne sanatları",
    "okuma kulübü",
    "satranç",
    "tasarım odaklı düşünme",
    "sürdürülebilirlik",
    "çevre",
    "iklim değişikliği",
    "politik aktivizm",
    "insan hakları",
    "hukuk",
    "ekonomi",
    "pazarlama",
    "finans",
    "yönetim",
    "insan kaynakları",
    "vergi",
    "yedek parça",
    # Academic departments (common)
    "bilgisayar mühendisliği",
    "elektrik elektronik mühendisliği",
    "endüstri mühendisliği",
    "makine mühendisliği",
    "inşaat mühendisliği",
    "kimya mühendisliği",
    "mimarlık",
    "işletme",
    "iktisat",
    "hukuk fakültesi",
    "tıp fakültesi",
    "psikoloji bölümü",
    "sosyoloji",
    "matematik",
    "fizik",
    "kimya",
    "biyoloji",
    "istatistik",
    "biyomedikal mühendisliği",
    "endüstri ürünleri tasarımı",
    "gıda mühendisliği",
    "çeşitlilik ve kapsayıcılık",
    # Technology / tools
    "python",
    "javascript",
    "react",
    "vue",
    "nodejs",
    "django",
    "flask",
    "docker",
    "kubernetes",
    "ci/cd",
    "git",
    "linux",
    "aws",
    "azure",
    "gcp",
    # Career skills
    "cv hazırlama",
    "mülakat",
    "networking",
    "sunum becerileri",
    "liderlik",
    "takım çalışması",
    "problem çözme",
    "yaratıcı düşünme",
    "veri analizi",
    "iş zekası",
    # Hobbies & lifestyle
    "yemek",
    "mutfak",
    "kültür",
    "seyahat",
    "doğa yürüyüşü",
    "kamp",
    "oyun geliştirme",
    "masa oyunları",
    "kodlama",
    "blockchain",
    "kripto",
    "biyoteknoloji",
    "enerji",
    "uzay teknolojileri",
    "dijital sanat",
    "3d modelleme",
]

def seed_tags(apps, schema_editor):
    Tag = apps.get_model("events", "Tag")
    for name in DEFAULT_TAGS:
        Tag.objects.get_or_create(name=name)

class Migration(migrations.Migration):
    dependencies = [
        ("events", "0004_previous"),
    ]
    operations = [
        migrations.RunPython(seed_tags),
    ]
