# Generated by Django 5.2.9 on 2025-12-19 19:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0004_seed_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="club",
            name="city",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
    ]
